name: Creepy Or Cool?
favicon: null
layout_spectrum: 0.7930732772219926
typography_spectrum: 0.9742397509980947
title: Creepy Or Cool?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#dbeeec'
    - '#303b37'
    - '#93aca8'
    - '#5d7567'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
